# Soal 1

In [1]:
import numpy as np

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# Buat sebuah variable array 1 dimensi, lalu coba konversikan ke dalam bentuk 2 dimensi
arr1 = np.arange(10).reshape(2,5)
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [4]:
#reshape merubah struktur dari array numpy menjadi (row, column) yang diinginkan. 
#Jika kita menulis -1 berarti numpy array akan secara otomatis menyesuaikan jumlah row atau column nya
arr1.reshape(-1,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Soal 2

In [5]:
arr2 = np.arange(4,13).reshape(-1,3)
arr2

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [6]:
#Indexing menggunakan [row, column] bisa menjadi berlipat jika kita memasukkan index yang sama di dalam list row atau column
#yang diinginkan

arr2[:,[1,2,0,0,1,2,1]]

array([[ 5,  6,  4,  4,  5,  6,  5],
       [ 8,  9,  7,  7,  8,  9,  8],
       [11, 12, 10, 10, 11, 12, 11]])

## Soal 3

In [7]:
arr3 = np.arange(9).reshape(-1,3)
arr3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
#Sama seperti indexing pada saat di list, bisa menggunakan ::-1 untuk melakukan reverse baik di tingkat row ataupun column
arr3[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

## Soal 4

In [9]:
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

array_of_arrays = np.array([arr1, arr2, arr3])
array_of_arrays

C:\Users\User\AppData\Local\Temp/ipykernel_4344/3722970344.py:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  array_of_arrays = np.array([arr1, arr2, arr3])


array([array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])],
      dtype=object)

In [10]:
array_of_arrays = np.concatenate([arr1, arr2, arr3])
array_of_arrays

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# arr = np.array([i for ar in array_of_arrays for i in ar])
# coba gunakan for untuk membuat output dibawah ini

larr = []
for arr in array_of_arrays:
    larr.append(arr)
    arrays = np.array(larr)
arrays

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])