## Soal Latihan 1

1. Buatalh sebuah array yang berdimensi nxn dimana dimensi tersebut merupakan inputan
2. Dari array tersebut, coba ubah dimensi array tersebut ke bentuk dimesni lain
3. Tampilkan setiap elemen dari array yang dibuat sebelumnya itu yang memiliki nilai lebih besar dari 1/2 nilai elemen maksimumnya
4. Buat array baru yang merupakan hasil perkalian dari elemen array sebelumnya

## Jawaban Soal Latihan 1

In [1]:
import numpy as np

### Nomor 1

In [24]:
n = int(input('Masukkan nilai n : '))
m = int(input('Masukkan nilai m : '))
nomor1 = np.random.randint(1,100,(n,m))
nomor1

Masukkan nilai n : 4
Masukkan nilai m : 5


array([[21,  3, 87, 59, 12],
       [93, 65, 89, 16, 60],
       [13, 86, 27, 25, 22],
       [89, 85, 97, 42, 88]])

### Nomor 2

In [25]:
n = int(input('Masukkan nilai n : '))
m = int(input('Masukkan nilai m : '))
nomor2 = nomor1.reshape(n,m)
nomor2

Masukkan nilai n : 5
Masukkan nilai m : 4


array([[21,  3, 87, 59],
       [12, 93, 65, 89],
       [16, 60, 13, 86],
       [27, 25, 22, 89],
       [85, 97, 42, 88]])

### Nomor 3

In [26]:
nomor3 = nomor2[nomor2 > nomor2.max()/2]
nomor3

array([87, 59, 93, 65, 89, 60, 86, 89, 85, 97, 88])

### Nomor 4

In [22]:
# Buat array baru yang merupakan hasil perkalian dari elemen array sebelumnya

nomor5 = nomor2[2:4,:] * nomor1[1:3,1:]
nomor5

array([[0.17605343, 0.16298573, 0.17088718],
       [0.00366337, 0.34860575, 0.02831221]])