## Soal Latihan NumPy
1. Buat sebuah array (zero/one) dengan panjang n, dimana nilai n ini diambil secara random antara 1 sampai 20
2. Acaklah 4 nilai bilanga bulat dari 1 sampai 100
3. Lakukan fancy indexing dari bilangan tersebut
4. Buat matriks 2D dan hitunglah rata-rata dari baris ke-1 dan ke-3

## Jawaban Soal

In [4]:
import numpy as np

### Nomor 1

In [9]:
n = np.random.randint(1,21)
ones = np.ones(n)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### Nomor 2

In [16]:
numbers = np.random.randint(1,100,4)
numbers

array([37, 80, 41, 79])

### Nomor 3

In [17]:
numbers[[3,1]]

array([79, 80])

In [26]:
numbers[[3,0,2]]

array([79, 37, 41])

### Nomor 4

In [27]:
n = int(input('Masukkan jumlah baris :'))
m = int(input('Masukkan jumlah kolom :'))

arr2D = np.random.randint(1,100,(n,m))

print(f'Matriks 2D :\n{arr2D}\n')
print(f'Rata-rata baris pertama : {arr2D[0].mean()}')
print(f'Rata-rata baris ketiga : {arr2D[2].mean()}')

Masukkan jumlah baris :4
Masukkan jumlah kolom :5
Matriks 2D :
[[83 31 80 11 48]
 [92 96 68 57 23]
 [ 6 68 42 65 93]
 [62 70  7 25 70]]

Rata-rata baris pertama : 50.6
Rata-rata baris ketiga : 54.8
