## Soal Latihan
1. Bisa/tidak dibuat array dari list yang isinya:
   - float semua ?
   - integer semua ?
   - boolean semua ?
   - float + integer ?
   - string
   - string float
2. Coba buat matrix yang semua isinya berisikan angka dari hasil dari ((1/2 x 100 + 1.5) ^ 1/2)
3. Kalikan hasil pada nomor 2 pada matrix identitas. Apakah hasilnya sama? Jika tidak Jelaskan kenapa ?
4. Bangkitkan data random dari 0 sampai 1 sebanyak 100 yang terbentuk menjadi sebuah matrix namun bukan matri (nxn) melainkan (mxn)
5. Apakah bisa dibangkitkan nilai random integer dari rentang 0.5 hingga 100 ? Jika iya coba lakukan
6. Bangkitkan data integer sebanyak x (inputan) dari n (inputan) hingga m (inputan)

## Jawaban Soal Latihan

In [1]:
import numpy as np

### Nomor 1

In [17]:
# Membuat array berisi float semua

list_float = [0.8, 0.9, 10.7, 12.6]
arr_float = np.array(list_float)
arr_float

array([ 0.8,  0.9, 10.7, 12.6])

In [21]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [26]:
# Membuat array berisi integer semua

list_int = [45,72,36,54,81]
arr_int = np.array(list_int)
arr_int

array([45, 72, 36, 54, 81])

In [22]:
np.random.randint(1,100,5)

array([30, 16, 60, 77, 43])

In [23]:
# Membuat array berisi boolean

list_bool = [True, False, True, True, True]
arr_bool = np.array(list_bool)
arr_bool

array([ True, False,  True,  True,  True])

In [36]:
# Membuat array berisi float dan integer

arr_float_int = np.array(list_float + list_int)               # array yang berisi float dan integer hasilnya akan bernilai float semua
arr_float_int

array([ 0.8,  0.9, 10.7, 12.6, 45. , 72. , 36. , 54. , 81. ])

In [35]:
list_floint = [100, 0.90, 54, 81, 30, 45.5, 53, 72, 85.5]     # array yang berisi float dan integer hasilnya akan bernilai float semua
arr_floint = np.array(list_floint)
arr_floint

array([100. ,   0.9,  54. ,  81. ,  30. ,  45.5,  53. ,  72. ,  85.5])

In [33]:
# Membuat matrix berisi string 

list_str = ['apel', 'anggur', 'jeruk', 'melon']
arr_str = np.array(list_str)
arr_str

array(['apel', 'anggur', 'jeruk', 'melon'], dtype='<U6')

In [34]:
list_strflo = ['mangga', 0.63, 7.2, 'jambu']
arr_strflo = np.array(list_strflo)
arr_strflo

array(['mangga', '0.63', '7.2', 'jambu'], dtype='<U32')

Berdasarkan hasil percobaan di atas dapat diketahui jika array bisa dibuat dari list yang berisi :
- float semua 
- integer semua 
- boolean semua 
- float + integer 
- string
- string float

### Nomor 2

In [37]:
nomor2 = np.ones((4,4)) * np.array((1/2 * 100 + 1.5) ** 1/2)
nomor2

array([[25.75, 25.75, 25.75, 25.75],
       [25.75, 25.75, 25.75, 25.75],
       [25.75, 25.75, 25.75, 25.75],
       [25.75, 25.75, 25.75, 25.75]])

### Nomor 3

In [38]:
nomor3 = nomor2 * np.eye(4)
nomor3

array([[25.75,  0.  ,  0.  ,  0.  ],
       [ 0.  , 25.75,  0.  ,  0.  ],
       [ 0.  ,  0.  , 25.75,  0.  ],
       [ 0.  ,  0.  ,  0.  , 25.75]])

Setelah matrix dari nomor2 dikalikan dengan matrik identitas maka hasilnya tidak sama. Karena matriks identitas adalah matriks bernilai 0 dengan determinan bernilai 1 sehingga apabila suatu matriks dikalikan matriks identitas maka determinan matriks tresebut akan bernilai tetap dan elemen selain determinan akan bernilai 0. Sehingga saat matriks nomor2 dikalikan dengan matriks identitas, maka hasiln nomor3 tidak sama seperti hasil nomor2.

### Nomor 4

In [39]:
nomor4 = np.random.randn(20,5)
nomor4

array([[-0.10552379,  2.06821365,  1.12330192, -0.11198154,  2.48134184],
       [ 0.7762877 ,  2.04751992, -0.24866766, -0.02925973,  0.48455383],
       [ 0.68798699, -0.85056821,  1.73363603, -1.50916054,  0.24375145],
       [-1.12214974,  0.51752897,  0.08413029,  1.09958079,  1.23256919],
       [ 0.44019258,  0.91078904, -0.26315832,  0.49718787, -0.35183814],
       [ 1.05313822, -0.32077622, -0.53916323,  0.09918225, -1.19690761],
       [-0.93727245,  0.45568274,  0.74575997, -1.08108446, -0.49237832],
       [-0.71213285, -0.16986283, -0.82879403, -1.68169619,  0.02057366],
       [-0.04771843, -0.05024678,  0.21703551, -0.52911749,  0.25771305],
       [-0.47710856, -0.97995611, -0.79971793, -1.56342465,  1.055284  ],
       [ 0.59924811, -0.34323954,  0.2396443 ,  1.4265334 , -0.7110036 ],
       [ 0.32789323,  0.79556907,  2.08565485,  0.05949655,  1.29847229],
       [-1.90660617, -0.55603248,  1.08774958, -1.11362247,  0.30630623],
       [ 0.3691262 , -0.25145043,  0.0

### Nomor 5

In [40]:
nomor5 = np.random.randint(0.5,100)
nomor5

22

### Nomor 6

In [41]:
n = int(input('Masukkan batas bawah : '))
m = int(input('Masukkan batas atas : '))
x = int(input('Masukkan banyak data yang ingin dibangkitkan : '))
nomor6= np.random.randint(n,m,x)
nomor6

Masukkan batas bawah : 1
Masukkan batas atas : 100
Masukkan banyak data yang ingin dibangkitkan : 50


array([31, 61, 58, 56, 87, 40,  7, 29, 81, 79,  7, 92, 80, 48,  1, 21, 64,
       65, 83, 69, 85, 92,  2, 53, 79, 19, 75, 12, 46, 60, 14, 27, 72, 60,
       44, 92, 67, 19, 51, 42, 89, 52, 57, 20, 24,  5, 21, 95, 68, 98])