## Soal Latihan 2
1. Buatlah sebuah array dengan rentang nilai antara 1 hingga 100 yang terbagi rata sebanyak 50 bagian.
2. Dari 50 bagian tersebut, buatlah sebuah matriks dengan ukuran nxm dimana nilai n<m. Ambil nilainya dari bilangan yang tersedia pada array sebelumnya
3. Tampilkan matriks tersebut 
4. Setelah itu, matriks yang sudah terbentuk tadi dibuat dalam bentuk 1 dimensi lagi lalu tampilkan :
    - Nilai maksimum dan minimumnya
    - Pada indeks keberapa nilai maksimum dan minimum tersebut
5. Jumlahkan antara nilai maksimum dan minimum tersebut
6. Buat sebuah array dengan panjang array adalah inputan (diinput secara manual)
7. Jika panjangnya genap, gantilah setengah di bagian akhir dari matriks tersebut angka 22, sedangkan jika panjangnya ganjil gantilah angkanya menjadi 23 dari indeks pertama hingga ((n+1)/2)
8. Tampilkan matriksnya
9. Tunjukkan bagian dari matriks yang nilainya >20
10. Tampilkan nilai yang > 20

## Jawaban Soal Latihan 2

In [33]:
import numpy as np

### Nomor 1

In [34]:
nomor1 = np.linspace(1,100,50)
nomor1

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

### Nomor 2 & 3

In [35]:
nomor2 = nomor1.reshape(2,25)
nomor3 = nomor2
nomor3

array([[  1.        ,   3.02040816,   5.04081633,   7.06122449,
          9.08163265,  11.10204082,  13.12244898,  15.14285714,
         17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
         25.24489796,  27.26530612,  29.28571429,  31.30612245,
         33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
         41.40816327,  43.42857143,  45.44897959,  47.46938776,
         49.48979592],
       [ 51.51020408,  53.53061224,  55.55102041,  57.57142857,
         59.59183673,  61.6122449 ,  63.63265306,  65.65306122,
         67.67346939,  69.69387755,  71.71428571,  73.73469388,
         75.75510204,  77.7755102 ,  79.79591837,  81.81632653,
         83.83673469,  85.85714286,  87.87755102,  89.89795918,
         91.91836735,  93.93877551,  95.95918367,  97.97959184,
        100.        ]])

### Nomor4

In [36]:
nomor4 = nomor2.reshape(50,)
nomor4

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

In [43]:
# nomor 4a & 4b

print(f'Nilai maksimal dari array adalah : {nomor4.max()}')
print(f'Nilai maksimal dari array array berapa pada indek ke-{nomor4.argmax()}')
print(f'Nilai maksimal dari array adalah : {nomor4.min()}')
print(f'Nilai maksimal dari array array berapa pada indek ke-{nomor4.argmin()}')

Nilai maksimal dari array adalah : 100.0
Nilai maksimal dari array array berapa pada indek ke-49
Nilai maksimal dari array adalah : 1.0
Nilai maksimal dari array array berapa pada indek ke-0


### Nomor 5

In [16]:
nomor5 = max(nomor4) + min(nomor4)
nomor5

101.0

### Nomor 6, 7 & 8

In [27]:
# nomor 6
n =int(input('Masukkan jumlah n: '))
arr = np.arange(n)

# nomor 7
if n % 2 == 0:
    arr[int(n/2):] = 22
else :
    arr[int((n+1)/2):] = 23

# nomor8
arr

Masukkan jumlah n: 19


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 23, 23, 23, 23, 23, 23, 23,
       23, 23])

### Nomor 9

In [30]:
nomor9 = arr > 20
nomor9

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

### Nomor 10

In [32]:
nomor10 = arr[arr > 20]
nomor10

array([23, 23, 23, 23, 23, 23, 23, 23, 23])