## Soal Latihan Numpy
Buatlah sebuah menu, dengan ketentuan
- Menu 1
  - Buat sebuah array dengan panjang array adalah inputan
  - Nilai dari array tersebut juga adalah inputan, sehingga nantinya akan menhinput array 1 persatu
  - Reshape array tersebut ke dalam matriks dengan ukuran bebas (optional dalam bentuk inputan)
- Menu 2
  - Buatlah sebuah matriks 5x5 dari array bilangan random dengan distribusi normal
  - Tampilkan nilai maksimalnya dan minimumnya
  - Kemudian untuk row 1 dikalikan 4, row 3 dikalikan 3, row 5 dikalikan 2
  - Tampilkan hasilnya
- Menu 3
  - Buatlah matriks 2x2
  - Buat invers dari matriks tersebut
- Menu 4
  - Buatlah matriks 3x3
  - Hitunglah determinan

## Jawaban Soal 

In [1]:
import numpy as np

### Menu 1

In [3]:
# buat array

n = int(input('Masukkan panjang array : '))
list_angka= []
for item in range(n):
    x = int(input('Masukkan angka : '))
    list_angka.append(x)
arr = np.array(list_angka)
arr

Masukkan panjang array : 6
Masukkan angka : 45
Masukkan angka : 36
Masukkan angka : 72
Masukkan angka : 18
Masukkan angka : 90
Masukkan angka : 54


array([45, 36, 72, 18, 90, 54])

In [4]:
# reshape array

n = int(input('Masukkan banyak baris : '))
m = int(input('Masukkan banyak kolom : '))
arr.reshape(n,m)

Masukkan banyak baris : 3
Masukkan banyak kolom : 2


array([[45, 36],
       [72, 18],
       [90, 54]])

### Menu 2

In [5]:
# buat matrix 

arr2 = np.random.randn(5,5)
arr2

array([[ 0.08972184,  0.08139506, -0.4150788 ,  0.33867229,  0.16006113],
       [-1.24945959,  1.0791434 , -0.48997016, -0.56727432, -0.93697616],
       [ 0.27699604, -0.98108038, -0.285838  , -1.77784471, -1.5801961 ],
       [ 0.15798119,  0.46513679, -0.7523442 ,  0.68098082, -0.02735877],
       [ 0.88043747, -0.68562509, -0.39509362, -0.18680185, -0.82001008]])

In [16]:
print(f'Nilai maksimal dari matriks adalah : {arr2.max()}')
print(f'Nilai maksimal dari matriks adalah : {arr2.min()}')

Nilai maksimal dari matriks adalah : 1.0791433965292725
Nilai maksimal dari matriks adalah : -1.7778447068258305


In [17]:
# row1 x 4, row3 x 3, row5 x 2
kali_arr2 = [[arr2[0] * 4],[arr2[2] * 3],[arr2[4] * 5]]

# tampilkan
kali_arr2

[[array([ 0.35888734,  0.32558025, -1.6603152 ,  1.35468917,  0.64024451])],
 [array([ 0.83098811, -2.94324115, -0.857514  , -5.33353412, -4.74058829])],
 [array([ 4.40218737, -3.42812544, -1.97546812, -0.93400927, -4.1000504 ])]]

### Menu 3

In [9]:
# buat array
arr3 = np.random.randint(1,100,4)
arr3

array([76, 87, 22, 64])

In [10]:
# reshap array jadi 2x2
arr3.reshape(2,2)

array([[76, 87],
       [22, 64]])

In [11]:
# invers arr3
arr3_inv = np.linalg.inv(arr3.reshape(2,2))
arr3_inv

array([[ 0.02169492, -0.02949153],
       [-0.00745763,  0.02576271]])

### Menu 4

In [12]:
# buat array
arr4 = np.random.randint(1,100,9)
arr4

array([66, 68, 92, 11,  5, 11,  5, 49, 21])

In [13]:
# reshap array jadi 3x3
arr4.reshape(3,3)

array([[66, 68, 92],
       [11,  5, 11],
       [ 5, 49, 21]])

In [14]:
# determinan arr4
arr4_det = np.linalg.det(arr4.reshape(3,3))
arr4_det

6675.999999999998