# Pertemuan 4 : Create NumPy

In [1]:
import numpy as np

#### Array 1D

In [2]:
# listku = list(range(1,4)) 
listku = [1,2,3]       
listku

[1, 2, 3]

In [3]:
arr_1D = np.array(listku)    # 1D array
arr_1D

array([1, 2, 3])

In [4]:
# listku * 5 error
arr_1D * 5

array([ 5, 10, 15])

#### Array 2D

In [5]:
list2D = [[1,2,3],[4,5,6],[7,8,9]]
list2D

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
arr_2D = np.array(list2D)        # 2D array
arr_2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
arr_2D * 5

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

#### Array 3D

In [8]:
list3D = [
    [[1,2,3],[4,5,6],[7,8,9]],
    [[10,11,12],[13,14,15],[16,17,18]],
    [[19,20,21],[22,23,24],[25,26,27]]
]
list3D

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
 [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
 [[19, 20, 21], [22, 23, 24], [25, 26, 27]]]

In [9]:
arr_3D = np.array(list3D)        # 3D array
arr_3D

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

### Numpy arange

In [12]:
A = np.arange(20)       # membuat array dari 0 sampai 20, dimana angka 20 tidak masuk
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [13]:
# np(start,end)

A = np.arange(0,20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [14]:
#np.arange(start,end,step)

np.arange(0,21,2)     # membuat array dari 0 sampai 21 dengan step 2 (start, stop,step)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

Note : 
<br>
- range(start,stop,step) = menghasilkan list
- arange(start,stop,step) = menghasilkan array

### Numpy zeros

#### Array Zeros 1D

In [15]:
# np.zeros(size)

np.zeros(5)

array([0., 0., 0., 0., 0.])

#### Array Zeros 2D

In [16]:
# np.zeros((nrow,ncol))

np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### Array Zeros 3D

In [17]:
# np.zeros((narr,nrow,ncoll))

np.zeros((2,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

### Numpy ones

#### Array Ones 1D

In [15]:
# np.ones(size)

np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Array Ones 2D

In [16]:
# np.ones((nrow,ncol))

np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [17]:
np.ones((10,10))*10

array([[10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.]])

#### Array Ones 3D

In [18]:
# np.ones((narr,nrow,ncol))

np.ones((5,2,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [19]:
np.ones((10,10)) * 5

array([[5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

### Numpy eye

In [18]:
# np.eye(size), size pada np.eye menyatakan nrow,ncol

np.eye(5)          # membangkitkan matrix identitas ukuran 5x5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
# np.eye(nrow,ncol)

np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
np.eye(3) * list2D         # tidak menghasilkan array list2, tidak seperti perkalian matrix pada matematika yang sebenarnya

array([[1., 0., 0.],
       [0., 5., 0.],
       [0., 0., 9.]])

### Numpy linspace

In [21]:
# Membuat array 1D dimulai dari start sampai end sebanyak n
# np.lisnpace(start,end,n)

np.linspace(0,10,3) # membuat angka dari 0 sampai 10 sebanyak 3 bagian

array([ 0.,  5., 10.])

In [22]:
np.linspace(0,1,50)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [24]:
np.linspace(0,8,10)

array([0.        , 0.88888889, 1.77777778, 2.66666667, 3.55555556,
       4.44444444, 5.33333333, 6.22222222, 7.11111111, 8.        ])

## Random

### np.random.rand
membangkitkan data random antara 0 sampai 1

In [25]:
np.random.rand(5)     # array 1D 

array([0.77803073, 0.17022516, 0.48692976, 0.82657042, 0.02134199])

In [26]:
np.random.rand(10)

array([0.84245192, 0.19876741, 0.19912884, 0.44280692, 0.85258693,
       0.69473054, 0.47922809, 0.60949396, 0.61999428, 0.50151588])

In [27]:
np.random.rand(5,5)   # array 2D

array([[0.03630556, 0.18269761, 0.01827376, 0.39609005, 0.04722145],
       [0.55032031, 0.39610605, 0.14988914, 0.56274379, 0.27673256],
       [0.37307765, 0.20671393, 0.39069272, 0.03077447, 0.95337979],
       [0.31779797, 0.28000423, 0.79468872, 0.64165204, 0.61659822],
       [0.18702747, 0.29551817, 0.53884916, 0.43125586, 0.32667062]])

In [28]:
np.random.rand(5,8)

array([[0.4602857 , 0.81113002, 0.92452372, 0.88273296, 0.88332359,
        0.40035906, 0.16712415, 0.8346018 ],
       [0.43089559, 0.47484117, 0.17659693, 0.17057881, 0.91539174,
        0.56904517, 0.75777657, 0.22202382],
       [0.93386576, 0.76589996, 0.6845498 , 0.12196725, 0.17785725,
        0.11624285, 0.35228555, 0.35927954],
       [0.75945596, 0.58992848, 0.69086761, 0.15462507, 0.72420745,
        0.86009184, 0.60475384, 0.94329584],
       [0.60997392, 0.49559958, 0.93595183, 0.59038218, 0.57770135,
        0.94049402, 0.99691888, 0.19010881]])

In [29]:
np.random.rand(6).reshape(2,3,1)   # array 3D

array([[[0.30832152],
        [0.11856889],
        [0.52555245]],

       [[0.98495513],
        [0.37699556],
        [0.10146946]]])

In [30]:
np.random.rand(36).reshape(3,4,3)

array([[[0.54895552, 0.39703001, 0.85915992],
        [0.61234212, 0.07446855, 0.51383966],
        [0.24880836, 0.71534412, 0.85467543],
        [0.03692883, 0.69492749, 0.2809193 ]],

       [[0.34056606, 0.15996058, 0.3376352 ],
        [0.37599416, 0.85259587, 0.29384845],
        [0.53925553, 0.00670689, 0.22078387],
        [0.96449847, 0.36095109, 0.4185322 ]],

       [[0.74524069, 0.13706531, 0.97533138],
        [0.296816  , 0.71110484, 0.82124584],
        [0.85625644, 0.40681675, 0.04979529],
        [0.4050348 , 0.77724369, 0.26118685]]])

### np.random.randn
membangkitkan array dari data random yang berdistribusi normal

In [23]:
np.random.randn(10)       # array 1D

array([ 0.86728558,  1.89449717, -0.0898739 , -0.68978863,  0.47973339,
        0.7661165 , -0.77074187, -0.51688737, -0.65789576,  0.11617651])

In [24]:
np.random.randn(10,10)     # array 2D

array([[ 0.61524421, -0.2688124 ,  0.71317572, -1.83404818,  1.39372175,
         1.47458758, -0.71929857, -1.06879798,  0.65941488, -1.71725559],
       [ 1.60281873, -0.24070649,  1.35118823,  1.19691484, -0.86201918,
         0.58107699, -3.57751767, -1.12489461, -1.23330653, -1.22550638],
       [-0.42405162,  0.07214081,  0.02307155,  0.32964788,  0.59215845,
        -0.41222449,  0.33060776, -0.37882785,  1.40286188,  2.0988686 ],
       [-0.32466335, -0.7314224 , -0.38370999,  0.24457787, -2.01583443,
         0.38589137,  0.24716761, -1.71855754,  1.07563325, -0.05142146],
       [-1.50404135,  0.80575749, -1.38546455, -0.42245934,  1.1299556 ,
        -0.11294299, -0.42889429, -0.40155775,  1.13603688, -0.2561167 ],
       [-0.58833567,  0.7780945 , -0.53622871, -1.9748471 , -0.49507628,
        -0.27367258,  0.92450625,  1.15807143,  0.0094651 , -0.34163963],
       [ 0.82997807,  1.10302409,  1.33083768,  0.40889315,  0.2125251 ,
         0.23547506, -0.68254984,  0.05245346

In [33]:
np.random.rand(10,10)

array([[0.50152344, 0.08456669, 0.10681208, 0.39737364, 0.61800734,
        0.64843612, 0.4426735 , 0.78103324, 0.15826102, 0.57661527],
       [0.13919923, 0.64946707, 0.10944825, 0.02117194, 0.71541364,
        0.46411763, 0.34975219, 0.48191436, 0.74481841, 0.34287407],
       [0.56636476, 0.21576349, 0.72225682, 0.13231902, 0.83468221,
        0.20210676, 0.38083369, 0.49700573, 0.93223671, 0.23394574],
       [0.71566319, 0.57126372, 0.73108675, 0.6580359 , 0.48372259,
        0.02202656, 0.15641719, 0.75186828, 0.87714448, 0.89104703],
       [0.74675861, 0.99848812, 0.63819656, 0.9797063 , 0.57298246,
        0.89931089, 0.04368382, 0.38012133, 0.71455184, 0.95896552],
       [0.72149939, 0.0898903 , 0.04014481, 0.42490847, 0.78237617,
        0.15452075, 0.9547999 , 0.86252099, 0.6474347 , 0.14659024],
       [0.08314679, 0.08534127, 0.71074705, 0.14873685, 0.41695087,
        0.77775096, 0.29526335, 0.28706612, 0.56024674, 0.00708887],
       [0.9491283 , 0.99016493, 0.6468261

### np.random.randint
membagkitkan data integer

In [26]:
np.random.randint(1,100)      # merandom dari 1 sampai 100 (start,end)

79

In [35]:
np.random.randint(1,100,10)   # merandom dari 1 sampai 100 dengan jumlah 10 dan membentuk array 1D

array([77, 91, 25, 57, 72, 14, 77, 79, 60, 33])

In [36]:
np.random.randint(1,100,10).reshape(5,2)   #jika ingin membentuk array 2D dapat gunakan reshape

array([[17, 86],
       [78, 37],
       [12, 88],
       [37, 66],
       [89, 65]])

## Attribute and Methods for Numpy Array

### .shape
digunakan untuk mengetahui ukuran atau dimensi dari array

In [27]:
my_list = list(range(1,4)) 
arr_1D = np.array(my_list)


list2 = [[1,2,3],[4,5,6],[7,8,9]]
arr_2D = np.array(list2)


list3 = [
    [[1,2,3],[4,5,6],[7,8,9]],
    [[10,11,12],[13,14,15],[16,17,18]],
    [[19,20,21],[22,23,24],[25,26,27]]
]
arr_3D = np.array(list3)

In [28]:
arr_1D.shape

(3,)

In [29]:
arr_2D.shape

(3, 3)

In [30]:
arr_3D.shape

(3, 3, 3)

### .reshape
digunakan untuk mengubah ukuran atau dimensi array

In [33]:
arr = np.arange(20)    # array 1D
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [34]:
arr.shape

(20,)

In [35]:
arr.reshape(1,20)      # array 2D

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [36]:
arr.reshape(1,20).shape

(1, 20)

In [45]:
arr.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [46]:
arr.reshape(20,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [47]:
arr.reshape(20,1).shape

(20, 1)

In [48]:
arr_2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
arr_2D.shape

(3, 3)

In [50]:
arr_2D.reshape(-1)   # perintah reshape(-1) akan mengembalikan dimensi array ke dimensi array 1D 

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
arr_2D.reshape(-1).shape

(9,)

In [52]:
arr_3D

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [53]:
arr_3D.shape

(3, 3, 3)

In [54]:
arr_3D.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [55]:
arr_3D.reshape(-1).shape

(27,)

In [56]:
A = np.random.randint(1,100,50)
A

array([24, 22, 57, 71, 24, 21, 20, 73, 26, 19, 55, 12,  8, 82, 39,  2, 34,
       72, 92, 12, 58, 33, 28,  9, 82, 18, 76, 52, 62, 20, 63, 14,  4, 93,
       85, 52, 75, 68, 70, 91, 70, 52, 20, 11, 48, 10,  4, 51, 43, 31])

In [57]:
A.shape

(50,)

In [58]:
Z = A.reshape(1,50)
Z

array([[24, 22, 57, 71, 24, 21, 20, 73, 26, 19, 55, 12,  8, 82, 39,  2,
        34, 72, 92, 12, 58, 33, 28,  9, 82, 18, 76, 52, 62, 20, 63, 14,
         4, 93, 85, 52, 75, 68, 70, 91, 70, 52, 20, 11, 48, 10,  4, 51,
        43, 31]])

In [59]:
Z.reshape(50)

array([24, 22, 57, 71, 24, 21, 20, 73, 26, 19, 55, 12,  8, 82, 39,  2, 34,
       72, 92, 12, 58, 33, 28,  9, 82, 18, 76, 52, 62, 20, 63, 14,  4, 93,
       85, 52, 75, 68, 70, 91, 70, 52, 20, 11, 48, 10,  4, 51, 43, 31])

### max, min, argmax, argmin

In [60]:
arr = np.random.randint(1,100,50)
arr

array([43, 99, 30, 96, 30, 96, 23, 57, 35, 83, 68, 57, 51, 80, 17, 45,  8,
       86, 60, 94,  1, 53, 41, 54, 41, 33, 59, 90, 71, 76, 93, 21, 94,  1,
       50, 87, 66, 58, 80, 20, 11, 31, 12, 11, 43, 24,  7, 62, 75, 51])

In [61]:
arr.max()      # untuk nilai maksimal pada array 1D

99

In [62]:
arr.argmax()      # untuk mengetahui index dari nilai maksimal pada array 1D

1

In [63]:
arr.min()      # untuk nilai minimal pada array 1D

1

In [64]:
arr.argmin()      # untuk mengetahui index dari nilai minimal pada array 1D

20

### .dtype 
digunakan untuk melihat tipe data dari suatu array

In [65]:
arr.dtype

dtype('int32')

In [66]:
newarr = np.random.randn(1,20)
newarr

array([[ 0.41321492,  1.4541567 ,  0.75160228,  0.43527882, -1.57416644,
        -0.46650737,  1.15479533,  0.77953518, -0.75326187, -0.76742127,
        -0.63749889,  1.44683263, -0.63705345,  1.93690819,  0.47048177,
         0.76134578,  1.68384275,  0.9635635 ,  1.68651695,  0.24417039]])

In [67]:
newarr.dtype

dtype('float64')

## Numpy Indexing and Selection

### Indexing Array 1D

In [68]:
arr

array([43, 99, 30, 96, 30, 96, 23, 57, 35, 83, 68, 57, 51, 80, 17, 45,  8,
       86, 60, 94,  1, 53, 41, 54, 41, 33, 59, 90, 71, 76, 93, 21, 94,  1,
       50, 87, 66, 58, 80, 20, 11, 31, 12, 11, 43, 24,  7, 62, 75, 51])

In [69]:
arr[6]      # melihat niai dari indek ke 6

23

In [70]:
arr[1:20]

array([99, 30, 96, 30, 96, 23, 57, 35, 83, 68, 57, 51, 80, 17, 45,  8, 86,
       60, 94])

In [71]:
arr[0:20]

array([43, 99, 30, 96, 30, 96, 23, 57, 35, 83, 68, 57, 51, 80, 17, 45,  8,
       86, 60, 94])

In [72]:
arr[7:10]   

array([57, 35, 83])

In [73]:
arr[40:-1]

array([11, 31, 12, 11, 43, 24,  7, 62, 75])

In [74]:
[arr[3], arr[7], arr[10]]

[96, 57, 68]

In [75]:
arr[[3,7,10]]    # fancy indexing

array([96, 57, 68])

In [76]:
arr[0:20:2]

array([43, 30, 30, 23, 35, 68, 51, 17,  8, 60])

In [77]:
arr[25:] = 0
arr

array([43, 99, 30, 96, 30, 96, 23, 57, 35, 83, 68, 57, 51, 80, 17, 45,  8,
       86, 60, 94,  1, 53, 41, 54, 41,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])

In [78]:
slice_of_arr = arr[0:10]
slice_of_arr

array([43, 99, 30, 96, 30, 96, 23, 57, 35, 83])

In [79]:
slice_of_arr[2:6] = 500
slice_of_arr

array([ 43,  99, 500, 500, 500, 500,  23,  57,  35,  83])

In [80]:
slice_of_arr[:] = 999
slice_of_arr

array([999, 999, 999, 999, 999, 999, 999, 999, 999, 999])

In [81]:
arr

array([999, 999, 999, 999, 999, 999, 999, 999, 999, 999,  68,  57,  51,
        80,  17,  45,   8,  86,  60,  94,   1,  53,  41,  54,  41,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0])

### Indexing Array 2D 

In [82]:
arr_2D = np.random.randint(1,100,50).reshape(10,5)
arr_2D

array([[52,  8, 45, 20, 75],
       [77, 81, 75,  3, 78],
       [29, 59, 26, 77, 89],
       [34, 57, 18, 27,  2],
       [62, 41, 62,  4, 80],
       [94, 48, 25, 93, 50],
       [59,  5,  3, 76, 65],
       [40, 59, 12, 91, 72],
       [25,  6, 94, 53, 28],
       [80,  6, 32,  9, 95]])

In [83]:
arr_2D[2]          # indexing row

array([29, 59, 26, 77, 89])

In [84]:
arr_2D[1][0]

77

In [85]:
arr_2D[1,0]

77

In [86]:
arr_2D[7:10, 2:]

array([[12, 91, 72],
       [94, 53, 28],
       [32,  9, 95]])

In [87]:
arr_2D[:5, 1:] 

array([[ 8, 45, 20, 75],
       [81, 75,  3, 78],
       [59, 26, 77, 89],
       [57, 18, 27,  2],
       [41, 62,  4, 80]])

In [88]:
arr_2D[:,2]

array([45, 75, 26, 18, 62, 25,  3, 12, 94, 32])

In [89]:
arr_2D[2, :]

array([29, 59, 26, 77, 89])

### Fancy Indexing

#### Array 1D

In [90]:
arr

array([999, 999, 999, 999, 999, 999, 999, 999, 999, 999,  68,  57,  51,
        80,  17,  45,   8,  86,  60,  94,   1,  53,  41,  54,  41,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0])

In [91]:
[arr[1], arr[5], arr[9]]     # normal indexing

[999, 999, 999]

In [92]:
arr[[1,5,9]]                 # fancy indexing

array([999, 999, 999])

#### Array 2D

In [93]:
arr_2D

array([[52,  8, 45, 20, 75],
       [77, 81, 75,  3, 78],
       [29, 59, 26, 77, 89],
       [34, 57, 18, 27,  2],
       [62, 41, 62,  4, 80],
       [94, 48, 25, 93, 50],
       [59,  5,  3, 76, 65],
       [40, 59, 12, 91, 72],
       [25,  6, 94, 53, 28],
       [80,  6, 32,  9, 95]])

In [94]:
arr_2D[[0,2]]

array([[52,  8, 45, 20, 75],
       [29, 59, 26, 77, 89]])

In [95]:
arr_2D[0:, 0:2]

array([[52,  8],
       [77, 81],
       [29, 59],
       [34, 57],
       [62, 41],
       [94, 48],
       [59,  5],
       [40, 59],
       [25,  6],
       [80,  6]])

### Conditional Selection

In [96]:
arr = np.random.randint(1,100,50)
arr

array([21, 56,  6, 67, 72, 97, 76, 76, 12, 99, 18, 74, 61, 64, 24, 71, 63,
       32, 63, 77, 79, 48,  4, 85,  9, 97, 33,  9, 41, 53, 50, 76, 68, 75,
       81, 24, 88, 49, 51, 73, 13, 53, 75, 30, 22, 50, 83, 61, 78, 73])

In [97]:
arr > 50

array([False,  True, False,  True,  True,  True,  True,  True, False,
        True, False,  True,  True,  True, False,  True,  True, False,
        True,  True,  True, False, False,  True, False,  True, False,
       False, False,  True, False,  True,  True,  True,  True, False,
        True, False,  True,  True, False,  True,  True, False, False,
       False,  True,  True,  True,  True])

In [98]:
bool_arr = arr > 50
bool_arr

array([False,  True, False,  True,  True,  True,  True,  True, False,
        True, False,  True,  True,  True, False,  True,  True, False,
        True,  True,  True, False, False,  True, False,  True, False,
       False, False,  True, False,  True,  True,  True,  True, False,
        True, False,  True,  True, False,  True,  True, False, False,
       False,  True,  True,  True,  True])

In [99]:
arr[bool_arr]

array([56, 67, 72, 97, 76, 76, 99, 74, 61, 64, 71, 63, 63, 77, 79, 85, 97,
       53, 76, 68, 75, 81, 88, 51, 73, 53, 75, 83, 61, 78, 73])

In [100]:
arr[arr < 50]

array([21,  6, 12, 18, 24, 32, 48,  4,  9, 33,  9, 41, 24, 49, 13, 30, 22])

In [101]:
x = 45
arr[arr > x]

array([56, 67, 72, 97, 76, 76, 99, 74, 61, 64, 71, 63, 63, 77, 79, 48, 85,
       97, 53, 50, 76, 68, 75, 81, 88, 49, 51, 73, 53, 75, 50, 83, 61, 78,
       73])

In [102]:
arr[(arr>50) & (A<70)]

array([56, 72, 97, 76, 99, 74, 61, 71, 63, 77, 79, 85, 97, 53, 76, 68, 53,
       75, 83, 61, 78, 73])

# Pertemuan 5 : Broadcasting and Other Function NumPy

## Broadcasting

In [103]:
A = np.array([[1,2,3],[3,4,5],[6,7,8]])
B = np.array([1,2,3])

In [104]:
A

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [105]:
B

array([1, 2, 3])

In [106]:
A * B

array([[ 1,  4,  9],
       [ 3,  8, 15],
       [ 6, 14, 24]])

## Arithmetics Operation

### Arithmentics Array 1D 

In [107]:
arr = np.random.randint(1,10,7)
arr

array([5, 6, 8, 9, 1, 6, 3])

In [108]:
arr + 1

array([ 6,  7,  9, 10,  2,  7,  4])

In [109]:
arr * 5

array([25, 30, 40, 45,  5, 30, 15])

In [110]:
arr * arr

array([25, 36, 64, 81,  1, 36,  9])

### Arithmetic Array 2D

In [111]:
A * 10

array([[10, 20, 30],
       [30, 40, 50],
       [60, 70, 80]])

In [112]:
1/A

array([[1.        , 0.5       , 0.33333333],
       [0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     ]])

In [113]:
A/A

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [114]:
A + 2

array([[ 3,  4,  5],
       [ 5,  6,  7],
       [ 8,  9, 10]])

### Mathematical Array Function

In [116]:
# akar
np.sqrt(A)

array([[1.        , 1.41421356, 1.73205081],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712]])

In [117]:
# eksponensial
np.exp(A)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [2.00855369e+01, 5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03]])

In [118]:
# trigonometri
np.sin(A)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [ 0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825]])

In [119]:
# logaritma
np.log(A)

array([[0.        , 0.69314718, 1.09861229],
       [1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154]])

## Other Function

### insert, delete, append

In [121]:
arr

array([5, 6, 8, 9, 1, 6, 3])

In [167]:
# jika 1D

np.insert(arr,9,100)             # menambahkan nilai 10 di ke-9 pada variabel 

array([  0,   1,   2,   3,   4,   5,   6,   7,   8, 100])

In [123]:
np.insert(arr,3,(arr[2]*3))     # tidak bersifat permanen, jika mau permanen dimasukkan ke dalam variable

array([ 5,  6,  8, 24,  9,  1,  6,  3])

In [124]:
# jika 2D

np.insert(A, 1, 10)

array([ 1, 10,  2,  3,  3,  4,  5,  6,  7,  8])

In [126]:
np.insert(A,1,10, axis=0)

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [127]:
A[1,1] = 10

In [130]:
A

array([[ 1,  2,  3],
       [ 3, 10,  5],
       [ 6,  7,  8]])

In [131]:
np.append(A, 1)      # menambahkan nilai 1 pada indek terakhir

array([ 1,  2,  3,  3, 10,  5,  6,  7,  8,  1])

In [132]:
np.delete(A, 7)    

array([ 1,  2,  3,  3, 10,  5,  6,  8])

### concatenate

In [182]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5,6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [188]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [189]:
np.concatenate((a, b.T), axis=None)

array([1, 2, 3, 4, 5, 6])

In [134]:
S = np.arange(10)
W = np.arange(10,20)

In [135]:
S

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [136]:
W

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [138]:
np.concatenate((S,W), axis=0)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [139]:
A

array([[ 1,  2,  3],
       [ 3, 10,  5],
       [ 6,  7,  8]])

In [146]:
F = np.arange(3).reshape(1,3)
F

array([[0],
       [1],
       [2]])

In [149]:
np.concatenate((A,F),axis=1)

array([[ 1,  2,  3,  0],
       [ 3, 10,  5,  1],
       [ 6,  7,  8,  2]])

In [150]:
A

array([[ 1,  2,  3],
       [ 3, 10,  5],
       [ 6,  7,  8]])

In [151]:
B = np.array([12,4,5]).reshape(1,3)
B

array([[12,  4,  5]])

In [152]:
np.concatenate((A,B.T), axis=1)

array([[ 1,  2,  3, 12],
       [ 3, 10,  5,  4],
       [ 6,  7,  8,  5]])

### where

In [153]:
arr

array([5, 6, 8, 9, 1, 6, 3])

In [154]:
np.where(arr>5, 1, arr)

array([5, 1, 1, 1, 1, 1, 3])

In [155]:
np.where(arr>5, 1, 0)

array([0, 1, 1, 1, 0, 1, 0])

In [156]:
arr_2D

array([[52,  8, 45, 20, 75],
       [77, 81, 75,  3, 78],
       [29, 59, 26, 77, 89],
       [34, 57, 18, 27,  2],
       [62, 41, 62,  4, 80],
       [94, 48, 25, 93, 50],
       [59,  5,  3, 76, 65],
       [40, 59, 12, 91, 72],
       [25,  6, 94, 53, 28],
       [80,  6, 32,  9, 95]])

In [157]:
np.where(arr_2D<5, arr_2D*2, arr_2D)

array([[52,  8, 45, 20, 75],
       [77, 81, 75,  6, 78],
       [29, 59, 26, 77, 89],
       [34, 57, 18, 27,  4],
       [62, 41, 62,  8, 80],
       [94, 48, 25, 93, 50],
       [59,  5,  6, 76, 65],
       [40, 59, 12, 91, 72],
       [25,  6, 94, 53, 28],
       [80,  6, 32,  9, 95]])

In [158]:
np.where(arr_2D<=5, 0, arr_2D)

array([[52,  8, 45, 20, 75],
       [77, 81, 75,  0, 78],
       [29, 59, 26, 77, 89],
       [34, 57, 18, 27,  0],
       [62, 41, 62,  0, 80],
       [94, 48, 25, 93, 50],
       [59,  0,  0, 76, 65],
       [40, 59, 12, 91, 72],
       [25,  6, 94, 53, 28],
       [80,  6, 32,  9, 95]])