## Soal Latihan

1. Buat 1 array 2D, 1 array 1D
2. Buat sebuah variabel baru dimana nilainya adalah pangkat dari array1 ** array2 yang dibuat sebelumnya
3. Buat array ketiga yang berisikan bil. bulat random dari 1 hingga 10, dimensi bebas
4. Buat sebuah variabel baru yang merupakan gabungan dari hasil perkalian array pada no 2 digabungkan dengan array no 3
5. Coba ubah nilai dari final array dengan kondisi
   - Jika ada nilai yang <10 maka diubah menjadi nilai yang < 10 dipangkatkan denggan 0
   - Jika ada nilai yang >10 dan <20 maka bilainya tetap
   - Jika  ada nilai yang >20 maka nilainya adalah akar dari nilai tersebut

## Jawaban

In [1]:
import numpy as np

### Nomor 1

In [6]:
# array 2D
arr2D = np.random.randint(1,100,9).reshape(3,3)

# array 1D
arr1D = np.random.randint(1,100,3)

print(f'Array 2D :\n{arr2D}\n')
print(f'Array 1D :\n{arr1D}')

Array 2D :
[[69  6 75]
 [33 46 21]
 [94 53 50]]

Array 1D :
[76 57 94]


### Nomor 2

In [21]:
# 2. Buat sebuah variabel baru dimana nilainya adalah pangkat dari array1 ** array2 yang dibuat sebelumnya

arr2 = arr2D ** arr1D
arr2

array([[-1254383535,           0,   795728073],
       [ 1936363905,           0,  -504167159],
       [          0,   -41042347,           0]], dtype=int32)

### Nomor 3

In [20]:
# 3. Buat array ketiga yang berisikan bil. bulat random dari 1 hingga 10, dimensi bebas
arr3 = np.random.randint(1,10,3).reshape(1,3)
arr3

array([[1, 6, 9]])

### Nomor 4

In [12]:
# 4. Buat sebuah variabel baru yang merupakan gabungan dari hasil perkalian array pada no 2 digabungkan dengan array no 3
arr4 = np.concatenate((arr2,arr3), axis=0)
arr4

array([[-1254383535,           0,   795728073],
       [ 1936363905,           0,  -504167159],
       [          0,   -41042347,           0],
       [          6,           7,           1]])

### Nomor 5

In [25]:
# 5. Coba ubah nilai dari final array dengan kondisi
#    - Jika ada nilai yang <10 maka diubah menjadi nilai yang < 10 dipangkatkan denggan 0
#    - Jika ada nilai yang >10 dan <20 maka bilainya tetap
#    - Jika  ada nilai yang >20 maka nilainya adalah akar dari nilai tersebut

arr5 = np.where(arr4<10,(arr4**0),(np.where(arr4<20,arr4,arr4**0.5)))
arr5

C:\Users\User\AppData\Local\Temp/ipykernel_152/565082800.py:6: RuntimeWarning: invalid value encountered in power
  arr5 = np.where(arr4<10,(arr4**0),(np.where(arr4<20,arr4,arr4**0.5)))


array([[1.00000000e+00, 1.00000000e+00, 2.82086524e+04],
       [4.40041351e+04, 1.00000000e+00, 1.00000000e+00],
       [1.00000000e+00, 1.00000000e+00, 1.00000000e+00],
       [1.00000000e+00, 1.00000000e+00, 1.00000000e+00]])