### Merging

In [2]:
import numpy as np
import pandas as pd

df1 = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
      'A':[1,2,3,4],
      'B':[5,6,7,8]})

In [3]:
df1

key  A  B
0  K0  1  5
1  K1  2  6
2  K2  3  7
3  K3  4  8

In [4]:
df2 = pd.DataFrame({'key': ['K4', 'K1', 'K2', 'K3'],
      'C':[10,20,30,40],
      'D':[50,60,70,80]})

In [5]:
df2

key   C   D
0  K4  10  50
1  K1  20  60
2  K2  30  70
3  K3  40  80

In [6]:
pd.merge(df1,df2,on='key')

key  A  B   C   D
0  K1  2  6  20  60
1  K2  3  7  30  70
2  K3  4  8  40  80

In [7]:
pd.merge(df1,df2, how='outer', on='key')

key    A    B     C     D
0  K0  1.0  5.0   NaN   NaN
1  K1  2.0  6.0  20.0  60.0
2  K2  3.0  7.0  30.0  70.0
3  K3  4.0  8.0  40.0  80.0
4  K4  NaN  NaN  10.0  50.0

In [8]:
pd.merge(df1,df2, how='left', on='key')

key  A  B     C     D
0  K0  1  5   NaN   NaN
1  K1  2  6  20.0  60.0
2  K2  3  7  30.0  70.0
3  K3  4  8  40.0  80.0

In [9]:
pd.merge(df1,df2, how='right', on='key')

key    A    B   C   D
0  K4  NaN  NaN  10  50
1  K1  2.0  6.0  20  60
2  K2  3.0  7.0  30  70
3  K3  4.0  8.0  40  80

In [10]:
df3 = pd.DataFrame({'keys': ['K4', 'K1', 'K2', 'K3'],
      'C':[10,20,30,40],
      'D':[50,60,70,80]})
df3

keys   C   D
0   K4  10  50
1   K1  20  60
2   K2  30  70
3   K3  40  80

In [11]:
pd.merge(df1,df3, how='left', left_on='key', right_on='keys')

key  A  B keys     C     D
0  K0  1  5  NaN   NaN   NaN
1  K1  2  6   K1  20.0  60.0
2  K2  3  7   K2  30.0  70.0
3  K3  4  8   K3  40.0  80.0

### Join

In [12]:
df4 = pd.DataFrame({'A':[1,2,3,4], 'B':[5,6,7,8]},index=['K0', 'K1', 'K2', 'K3'])
df4

A  B
K0  1  5
K1  2  6
K2  3  7
K3  4  8

In [13]:
df5 = pd.DataFrame({'C':[11,12,13,14], 'D':[15,16,17,18]},index=['K4', 'K1', 'K2', 'K3'])
df5

C   D
K4  11  15
K1  12  16
K2  13  17
K3  14  18

In [14]:
df4.join(df5)

A  B     C     D
K0  1  5   NaN   NaN
K1  2  6  12.0  16.0
K2  3  7  13.0  17.0
K3  4  8  14.0  18.0

In [15]:
df4.join(df5, how='inner')

A  B   C   D
K1  2  6  12  16
K2  3  7  13  17
K3  4  8  14  18

In [16]:
df1

key  A  B
0  K0  1  5
1  K1  2  6
2  K2  3  7
3  K3  4  8

In [17]:
df2

key   C   D
0  K4  10  50
1  K1  20  60
2  K2  30  70
3  K3  40  80

### Concat

In [18]:
pd.concat([df1,df2])

key    A    B     C     D
0  K0  1.0  5.0   NaN   NaN
1  K1  2.0  6.0   NaN   NaN
2  K2  3.0  7.0   NaN   NaN
3  K3  4.0  8.0   NaN   NaN
0  K4  NaN  NaN  10.0  50.0
1  K1  NaN  NaN  20.0  60.0
2  K2  NaN  NaN  30.0  70.0
3  K3  NaN  NaN  40.0  80.0

In [41]:
pd.concat([df1,df2], axis=1)

key  A  B key   C   D
0  K0  1  5  K4  10  50
1  K1  2  6  K1  20  60
2  K2  3  7  K2  30  70
3  K3  4  8  K3  40  80

## Latihan Merge, Join dan Concat
1. Gunakan dataframe/dataset yang kemarin di download dari kaggle
2. Dari dataset tersebut, buatlah dataframe baru dengan ukuran 10x3 sebanyak 2 dataframe
3. Lakukan joining (bebas dengan menggunakan Merge ataupun join). Lakukan left, right, inner, outer join. Buat setiap joinnya kedalam sebuah variabel
4. Tempelkan juga hasil setiap join yang dibuat menjadi 1 dataframe 

### Nomor 1

In [20]:
data = pd.read_csv('Top250.csv')
data

Rank           Restaurant  \
0       1           McDonald's   
1       2            Starbucks   
2       3          Chick-fil-A   
3       4            Taco Bell   
4       5          Burger King   
..    ...                  ...   
245   246      Rainforest Cafe   
246   247                  PDQ   
247   248        Lupe Tortilla   
248   249  Cook-Out Restaurant   
249   250             Jollibee   

                                               Content  Sales YOY_Sales  \
0                                                  NaN  40412      4.9%   
1                                                  NaN  21380      8.6%   
2    While Popeyes got a lot of the chicken buzz in...  11320     13.0%   
3                                                  NaN  11293      9.0%   
4                                                  NaN  10204      2.7%   
..                                                 ...    ...       ...   
245                                                NaN    129    -10.4%   
246                                                NaN    127     -5.5%   
247                                                NaN    127     12.1%   
248                                                NaN    126     10.1%   
249                                                NaN    126     15.2%   

     Units YOY_Units Headquarters             Segment_Category  
0    13846     -0.5%          NaN       Quick Service & Burger  
1    15049      3.0%          NaN  Quick Service & Coffee Cafe  
2     2470      5.0%          NaN      Quick Service & Chicken  
3     6766      2.7%          NaN      Quick Service & Mexican  
4     7346      0.2%          NaN       Quick Service & Burger  
..     ...       ...          ...                          ...  
245     18     -5.3%          NaN                  Varied Menu  
246     56    -11.1%          NaN                      Chicken  
247     25      8.7%          NaN                      Mexican  
248    270      7.1%          NaN                       Burger  
249     40     11.1%          NaN                      Chicken  

[250 rows x 9 columns]

In [21]:
data.head()

Rank   Restaurant                                            Content  \
0     1   McDonald's                                                NaN   
1     2    Starbucks                                                NaN   
2     3  Chick-fil-A  While Popeyes got a lot of the chicken buzz in...   
3     4    Taco Bell                                                NaN   
4     5  Burger King                                                NaN   

   Sales YOY_Sales  Units YOY_Units Headquarters             Segment_Category  
0  40412      4.9%  13846     -0.5%          NaN       Quick Service & Burger  
1  21380      8.6%  15049      3.0%          NaN  Quick Service & Coffee Cafe  
2  11320     13.0%   2470      5.0%          NaN      Quick Service & Chicken  
3  11293      9.0%   6766      2.7%          NaN      Quick Service & Mexican  
4  10204      2.7%   7346      0.2%          NaN       Quick Service & Burger

### Nomor 2

In [22]:
df1 = data.iloc[:,[0,1,8]].head(10)
df1

Rank    Restaurant             Segment_Category
0     1    McDonald's       Quick Service & Burger
1     2     Starbucks  Quick Service & Coffee Cafe
2     3   Chick-fil-A      Quick Service & Chicken
3     4     Taco Bell      Quick Service & Mexican
4     5   Burger King       Quick Service & Burger
5     6        Subway     Quick Service & Sandwich
6     7       Wendy's       Quick Service & Burger
7     8       Dunkin'  Quick Service & Coffee Cafe
8     9      Domino's        Quick Service & Pizza
9    10  Panera Bread    Fast Casual & Bakery Cafe

In [23]:
df2 = data.iloc[:,[3,5,8]].tail(10)
df2

Sales  Units Segment_Category
240    131     31      Varied Menu
241    129    240      Coffee Cafe
242    129     93          Mexican
243    129    195              BBQ
244    129     52            Asian
245    129     18      Varied Menu
246    127     56          Chicken
247    127     25          Mexican
248    126    270           Burger
249    126     40          Chicken

### Nomor 3

In [101]:
inner_join = pd.merge(df1,df2,on='Segment_Category')
inner_join

Empty DataFrame
Columns: [Rank, Restaurant, Segment_Category, Sales, Units]
Index: []

In [102]:
outer_join = pd.merge(df1,df2, how = 'outer', on='Segment_Category')
outer_join

Rank    Restaurant             Segment_Category  Sales  Units
0    1.0    McDonald's       Quick Service & Burger    NaN    NaN
1    5.0   Burger King       Quick Service & Burger    NaN    NaN
2    7.0       Wendy's       Quick Service & Burger    NaN    NaN
3    2.0     Starbucks  Quick Service & Coffee Cafe    NaN    NaN
4    8.0       Dunkin'  Quick Service & Coffee Cafe    NaN    NaN
5    3.0   Chick-fil-A      Quick Service & Chicken    NaN    NaN
6    4.0     Taco Bell      Quick Service & Mexican    NaN    NaN
7    6.0        Subway     Quick Service & Sandwich    NaN    NaN
8    9.0      Domino's        Quick Service & Pizza    NaN    NaN
9   10.0  Panera Bread    Fast Casual & Bakery Cafe    NaN    NaN
10   NaN           NaN                  Varied Menu  131.0   31.0
11   NaN           NaN                  Varied Menu  129.0   18.0
12   NaN           NaN                  Coffee Cafe  129.0  240.0
13   NaN           NaN                      Mexican  129.0   93.0
14   NaN           NaN                      Mexican  127.0   25.0
15   NaN           NaN                          BBQ  129.0  195.0
16   NaN           NaN                        Asian  129.0   52.0
17   NaN           NaN                      Chicken  127.0   56.0
18   NaN           NaN                      Chicken  126.0   40.0
19   NaN           NaN                       Burger  126.0  270.0

In [103]:
left_join = pd.merge(df1,df2, how = 'left', on='Segment_Category')
left_join

Rank    Restaurant             Segment_Category  Sales  Units
0     1    McDonald's       Quick Service & Burger    NaN    NaN
1     2     Starbucks  Quick Service & Coffee Cafe    NaN    NaN
2     3   Chick-fil-A      Quick Service & Chicken    NaN    NaN
3     4     Taco Bell      Quick Service & Mexican    NaN    NaN
4     5   Burger King       Quick Service & Burger    NaN    NaN
5     6        Subway     Quick Service & Sandwich    NaN    NaN
6     7       Wendy's       Quick Service & Burger    NaN    NaN
7     8       Dunkin'  Quick Service & Coffee Cafe    NaN    NaN
8     9      Domino's        Quick Service & Pizza    NaN    NaN
9    10  Panera Bread    Fast Casual & Bakery Cafe    NaN    NaN

In [104]:
right_join = pd.merge(df1,df2, how = 'right', on='Segment_Category')
right_join

Rank Restaurant Segment_Category  Sales  Units
0   NaN        NaN      Varied Menu    131     31
1   NaN        NaN      Varied Menu    129     18
2   NaN        NaN      Coffee Cafe    129    240
3   NaN        NaN          Mexican    129     93
4   NaN        NaN          Mexican    127     25
5   NaN        NaN              BBQ    129    195
6   NaN        NaN            Asian    129     52
7   NaN        NaN          Chicken    127     56
8   NaN        NaN          Chicken    126     40
9   NaN        NaN           Burger    126    270

### Nomor 4

In [112]:
df3 = data.iloc[:,3:6].tail(10)
df3

Sales YOY_Sales  Units
240    131      4.5%     31
241    129      3.8%    240
242    129      5.2%     93
243    129      5.1%    195
244    129     18.6%     52
245    129    -10.4%     18
246    127     -5.5%     56
247    127     12.1%     25
248    126     10.1%    270
249    126     15.2%     40

In [113]:
df1.join(df3)

Rank    Restaurant             Segment_Category  Sales YOY_Sales  Units
0     1    McDonald's       Quick Service & Burger    NaN       NaN    NaN
1     2     Starbucks  Quick Service & Coffee Cafe    NaN       NaN    NaN
2     3   Chick-fil-A      Quick Service & Chicken    NaN       NaN    NaN
3     4     Taco Bell      Quick Service & Mexican    NaN       NaN    NaN
4     5   Burger King       Quick Service & Burger    NaN       NaN    NaN
5     6        Subway     Quick Service & Sandwich    NaN       NaN    NaN
6     7       Wendy's       Quick Service & Burger    NaN       NaN    NaN
7     8       Dunkin'  Quick Service & Coffee Cafe    NaN       NaN    NaN
8     9      Domino's        Quick Service & Pizza    NaN       NaN    NaN
9    10  Panera Bread    Fast Casual & Bakery Cafe    NaN       NaN    NaN

In [114]:
df1.join(df3, how='outer')

Rank    Restaurant             Segment_Category  Sales YOY_Sales  Units
0     1.0    McDonald's       Quick Service & Burger    NaN       NaN    NaN
1     2.0     Starbucks  Quick Service & Coffee Cafe    NaN       NaN    NaN
2     3.0   Chick-fil-A      Quick Service & Chicken    NaN       NaN    NaN
3     4.0     Taco Bell      Quick Service & Mexican    NaN       NaN    NaN
4     5.0   Burger King       Quick Service & Burger    NaN       NaN    NaN
5     6.0        Subway     Quick Service & Sandwich    NaN       NaN    NaN
6     7.0       Wendy's       Quick Service & Burger    NaN       NaN    NaN
7     8.0       Dunkin'  Quick Service & Coffee Cafe    NaN       NaN    NaN
8     9.0      Domino's        Quick Service & Pizza    NaN       NaN    NaN
9    10.0  Panera Bread    Fast Casual & Bakery Cafe    NaN       NaN    NaN
240   NaN           NaN                          NaN  131.0      4.5%   31.0
241   NaN           NaN                          NaN  129.0      3.8%  240.0
242   NaN           NaN                          NaN  129.0      5.2%   93.0
243   NaN           NaN                          NaN  129.0      5.1%  195.0
244   NaN           NaN                          NaN  129.0     18.6%   52.0
245   NaN           NaN                          NaN  129.0    -10.4%   18.0
246   NaN           NaN                          NaN  127.0     -5.5%   56.0
247   NaN           NaN                          NaN  127.0     12.1%   25.0
248   NaN           NaN                          NaN  126.0     10.1%  270.0
249   NaN           NaN                          NaN  126.0     15.2%   40.0

In [24]:
pd.concat([df1,df2])

Rank    Restaurant             Segment_Category  Sales  Units
0     1.0    McDonald's       Quick Service & Burger    NaN    NaN
1     2.0     Starbucks  Quick Service & Coffee Cafe    NaN    NaN
2     3.0   Chick-fil-A      Quick Service & Chicken    NaN    NaN
3     4.0     Taco Bell      Quick Service & Mexican    NaN    NaN
4     5.0   Burger King       Quick Service & Burger    NaN    NaN
5     6.0        Subway     Quick Service & Sandwich    NaN    NaN
6     7.0       Wendy's       Quick Service & Burger    NaN    NaN
7     8.0       Dunkin'  Quick Service & Coffee Cafe    NaN    NaN
8     9.0      Domino's        Quick Service & Pizza    NaN    NaN
9    10.0  Panera Bread    Fast Casual & Bakery Cafe    NaN    NaN
240   NaN           NaN                  Varied Menu  131.0   31.0
241   NaN           NaN                  Coffee Cafe  129.0  240.0
242   NaN           NaN                      Mexican  129.0   93.0
243   NaN           NaN                          BBQ  129.0  195.0
244   NaN           NaN                        Asian  129.0   52.0
245   NaN           NaN                  Varied Menu  129.0   18.0
246   NaN           NaN                      Chicken  127.0   56.0
247   NaN           NaN                      Mexican  127.0   25.0
248   NaN           NaN                       Burger  126.0  270.0
249   NaN           NaN                      Chicken  126.0   40.0

In [59]:
# # np.array(data[0:30]['Sales']).reshape(10,3)

# df1 = pd.DataFrame(data=np.array(data[0:30]['Sales']).reshape(10,3), index=range(1,11), columns=['A','B','C'])
# df1

A      B      C
1   40412  21380  11320
2   11293  10204  10200
3    9762   9228   7044
4    5890   5558   5509
5    4687   4546   4287
6    4085   3946   3884
7    3812   3811   3760
8    3669   3563   3504
9    3266   3016   2691
10   2638   2635   2556

In [60]:
# df2 = pd.DataFrame(data=np.array(data[0:30]['Units']).reshape(10,3), index=range(1,21,2), columns=['A','B','E'])
# df2

A      B      E
1   13846  15049   2470
3    6766   7346  23801
5    5852   9630   6126
7    2160   7306   2584
9    3526   4065    866
11   1665   2209   3359
13   2476   4237   4381
15   1206   1242   2243
17   1710    553   1558
19   3142    724    830

In [66]:
inner_join = pd.merge(df1,df2,on='A')
inner_join

Empty DataFrame
Columns: [A, B_x, C, B_y, E]
Index: []

In [69]:
new_df = pd.DataFrame(np.random.randint(1,100,(5,5)), columns= 'V W X Y Z'.split())
new_df

V   W   X   Y   Z
0  49   8  86  15  44
1  40  68  43  54  17
2  26  63  46  60  64
3  13  51   8  31  87
4  52  82  14  70  27

In [70]:
def mod(x):
    return x%2

In [71]:
new_df['V'].apply(mod)

0    1
1    0
2    0
3    1
4    0
Name: V, dtype: int64

In [83]:
def times(x):
    return new_df['X'] *  new_df['Y']
    
#     return X * Y

In [84]:
new_df[['V','X']].apply(times)

V     X
0  1290  1290
1  2322  2322
2  2760  2760
3   248   248
4   980   980

In [80]:
new_df['V'].apply(print)

49
40
26
13
52


0    None
1    None
2    None
3    None
4    None
Name: V, dtype: object

In [91]:
new_df

V   W   X   Y   Z
0  49   8  86  15  44
1  40  68  43  54  17
2  26  63  46  60  64
3  13  51   8  31  87
4  52  82  14  70  27

In [87]:
def times(X,Y):
    return X * Y

In [88]:
new_df['V'].apply(times, Y=new_df['Y'])

0     1     2     3     4
0  735  2646  2940  1519  3430
1  600  2160  2400  1240  2800
2  390  1404  1560   806  1820
3  195   702   780   403   910
4  780  2808  3120  1612  3640

In [89]:
def times(X,Y,Z):
    return X * Y * Z

In [90]:
new_df['V'].apply(times, Y=new_df['Y'], Z=new_df['Z'])

0      1       2       3      4
0  32340  44982  188160  132153  92610
1  26400  36720  153600  107880  75600
2  17160  23868   99840   70122  49140
3   8580  11934   49920   35061  24570
4  34320  47736  199680  140244  98280

## Latihan 1
1. Buatlah sebuah variabel input untuk menentukan jumlah baris yang akan dibuat
1. Buatlah sebuah dataframe dengan ketentuan :
    - Kolom 1 merupakan data random normal sebanyak n baris (inputan)
    - Kolom 2 merupakan data random antara 0 sampai 1 sebanyak n baris
    - Kolom 3 merupakan data random antara 1 hingga 10 sebanyak n baris (gunakan random uniform pada numpy)
    - Kolom 4 merupakan hasil penjumlahan antara kolom 1 dan kolom 3
    - Kolom 5 merupakan hasil bagi yang dibulatkan kebawah antara kolom 2 dan kolom 3
    - Kolom 6 merupakan hasil bagi yang dibulatkan keatas antara kolom 4 dan kolom 5
    - Kolom 7 merupakan hasil perkalian antara pi dengan kolom 6
1. Tambahkan satu kolom baru yang nilainya bebas dan unique. Kolom baru ini kemudian di set sebagai index nya.
1. Buatlah sebuah fungsi. Fungsi yang dibuat bebas. Coba libatkan 2 kolom dalam fungsi ini. Lalu buatlah variabel baru yang merupakan implementasi dari fungsi yang telah dibuat.
1. Buat sebuah dataframe baru yang berukuran

In [25]:
import math as mt

### Nomor 1

In [26]:
n = int((input('Masukkan jumlah baris yang diinginkan : ')))

Masukkan jumlah baris yang diinginkan : 10


### Nomor 2

In [27]:
dflat1 = pd.DataFrame()
dflat1

dflat1['col1'] = np.random.randn(n)
dflat1['col2'] = np.random.rand(n)
dflat1['col3'] = np.random.uniform(1,10,n)
dflat1['col4'] = np.array(dflat1['col1'] * dflat1['col3'])
dflat1['col5'] = np.array(dflat1['col1'] + dflat1['col3'])
dflat1['col6'] = np.array(dflat1['col4']//dflat1['col5'])
dflat1['col7'] = np.array(mt.pi * dflat1['col5'])

In [28]:
dflat1

col1      col2      col3      col4      col5  col6       col7
0 -0.359124  0.925168  8.472249 -3.042585  8.113126  -1.0  25.488136
1  0.321350  0.278386  2.751648  0.884243  3.072998   0.0   9.654109
2  0.384881  0.001005  1.011877  0.389453  1.396759   0.0   4.388046
3 -0.403692  0.020898  4.902185 -1.978975  4.498493  -1.0  14.132432
4  0.256317  0.011739  2.283360  0.585264  2.539677   0.0   7.978631
5 -0.685369  0.255230  4.168593 -2.857023  3.483225  -1.0  10.942874
6  0.968826  0.315908  5.891862  5.708186  6.860687   0.0  21.553484
7 -0.877497  0.311783  8.805173 -7.726511  7.927676  -1.0  24.905530
8  0.095380  0.610503  7.507361  0.716050  7.602740   0.0  23.884713
9  0.776449  0.263205  1.061522  0.824218  1.837971   0.0   5.774156

### Nomor 3

In [29]:
import random
import string
# random.seed(10)
rand_letters = random.choices(string.ascii_lowercase,k=n)
rand_letters

['r', 'y', 'v', 'a', 'm', 'q', 'x', 'd', 'z', 'c']

In [30]:
dflat1['unique'] = rand_letters

In [31]:
dflat1

col1      col2      col3      col4      col5  col6       col7 unique
0 -0.359124  0.925168  8.472249 -3.042585  8.113126  -1.0  25.488136      r
1  0.321350  0.278386  2.751648  0.884243  3.072998   0.0   9.654109      y
2  0.384881  0.001005  1.011877  0.389453  1.396759   0.0   4.388046      v
3 -0.403692  0.020898  4.902185 -1.978975  4.498493  -1.0  14.132432      a
4  0.256317  0.011739  2.283360  0.585264  2.539677   0.0   7.978631      m
5 -0.685369  0.255230  4.168593 -2.857023  3.483225  -1.0  10.942874      q
6  0.968826  0.315908  5.891862  5.708186  6.860687   0.0  21.553484      x
7 -0.877497  0.311783  8.805173 -7.726511  7.927676  -1.0  24.905530      d
8  0.095380  0.610503  7.507361  0.716050  7.602740   0.0  23.884713      z
9  0.776449  0.263205  1.061522  0.824218  1.837971   0.0   5.774156      c

In [32]:
dflat1.set_index('unique')

col1      col2      col3      col4      col5  col6       col7
unique                                                                   
r      -0.359124  0.925168  8.472249 -3.042585  8.113126  -1.0  25.488136
y       0.321350  0.278386  2.751648  0.884243  3.072998   0.0   9.654109
v       0.384881  0.001005  1.011877  0.389453  1.396759   0.0   4.388046
a      -0.403692  0.020898  4.902185 -1.978975  4.498493  -1.0  14.132432
m       0.256317  0.011739  2.283360  0.585264  2.539677   0.0   7.978631
q      -0.685369  0.255230  4.168593 -2.857023  3.483225  -1.0  10.942874
x       0.968826  0.315908  5.891862  5.708186  6.860687   0.0  21.553484
d      -0.877497  0.311783  8.805173 -7.726511  7.927676  -1.0  24.905530
z       0.095380  0.610503  7.507361  0.716050  7.602740   0.0  23.884713
c       0.776449  0.263205  1.061522  0.824218  1.837971   0.0   5.774156

### Nomor 4

In [180]:
def kurang(x):
    return x['col3'] - x['col6']

In [183]:
dflat1['col8'] = dflat1[['col3','col6']].apply(kurang, axis=1)

# dflat1['col8'].apply(kurang)

In [184]:
dflat1

col1      col2      col3      col4      col5  col6       col7 unique  \
0  0.177947  0.225362  1.601452  0.284973  1.779399   0.0   5.590145      w   
1  0.184288  0.011343  2.380143  0.438632  2.564432   0.0   8.056399      p   
2  0.905873  0.909118  8.167601  7.398806  9.073474   0.0  28.505159      j   
3 -0.002695  0.693479  1.567220 -0.004224  1.564524  -1.0   4.915098      h   
4  0.702357  0.241503  2.689671  1.889109  3.392028   0.0  10.656370      r   
5  0.341921  0.182778  9.295631  3.178375  9.637553   0.0  30.277264      l   
6  1.257795  0.049831  3.571635  4.492386  4.829430   0.0  15.172103      r   
7 -0.241723  0.720601  5.850922 -1.414302  5.609199  -1.0  17.621818      r   
8  0.913589  0.654422  2.926981  2.674059  3.840571   0.0  12.065509      d   
9  0.199781  0.433508  9.528417  1.903597  9.728198   0.0  30.562035      t   

       col8  
0  1.601452  
1  2.380143  
2  8.167601  
3  2.567220  
4  2.689671  
5  9.295631  
6  3.571635  
7  6.850922  
8  2.926981  
9  9.528417

In [185]:
df2lat1 = pd.DataFrame()
df2lat1

df2lat1['col1'] = np.random.randn(n)
df2lat1['col2'] = np.random.rand(n)
df2lat1['col3'] = np.random.uniform(1,10,n)
df2lat1['col4'] = np.random.randint(100,1000,n)
df2lat1['col5'] = np.linspace(1,100,n)
df2lat1['col6'] = np.ones(n)
df2lat1['col7'] = np.arange(n)
df2lat1['col8'] = np.zeros(n)

In [186]:
df2lat1

col1      col2      col3  col4   col5  col6  col7  col8
0  0.097709  0.494965  8.343930   586    1.0   1.0     0   0.0
1  1.101432  0.883264  1.675685   900   12.0   1.0     1   0.0
2 -1.433290  0.290166  9.889572   759   23.0   1.0     2   0.0
3 -1.385835  0.268615  9.761493   440   34.0   1.0     3   0.0
4  1.309157  0.381069  3.225178   441   45.0   1.0     4   0.0
5  0.990086  0.877716  3.463870   545   56.0   1.0     5   0.0
6 -0.073939  0.177413  2.559143   705   67.0   1.0     6   0.0
7 -0.945785  0.423090  2.602685   203   78.0   1.0     7   0.0
8 -0.763080  0.882092  8.879926   773   89.0   1.0     8   0.0
9  0.426709  0.692333  4.066110   498  100.0   1.0     9   0.0

In [187]:
concatedf = pd.concat([dflat1,df2lat1])
concatedf

col1      col2      col3        col4        col5  col6       col7  \
0  0.177947  0.225362  1.601452    0.284973    1.779399   0.0   5.590145   
1  0.184288  0.011343  2.380143    0.438632    2.564432   0.0   8.056399   
2  0.905873  0.909118  8.167601    7.398806    9.073474   0.0  28.505159   
3 -0.002695  0.693479  1.567220   -0.004224    1.564524  -1.0   4.915098   
4  0.702357  0.241503  2.689671    1.889109    3.392028   0.0  10.656370   
5  0.341921  0.182778  9.295631    3.178375    9.637553   0.0  30.277264   
6  1.257795  0.049831  3.571635    4.492386    4.829430   0.0  15.172103   
7 -0.241723  0.720601  5.850922   -1.414302    5.609199  -1.0  17.621818   
8  0.913589  0.654422  2.926981    2.674059    3.840571   0.0  12.065509   
9  0.199781  0.433508  9.528417    1.903597    9.728198   0.0  30.562035   
0  0.097709  0.494965  8.343930  586.000000    1.000000   1.0   0.000000   
1  1.101432  0.883264  1.675685  900.000000   12.000000   1.0   1.000000   
2 -1.433290  0.290166  9.889572  759.000000   23.000000   1.0   2.000000   
3 -1.385835  0.268615  9.761493  440.000000   34.000000   1.0   3.000000   
4  1.309157  0.381069  3.225178  441.000000   45.000000   1.0   4.000000   
5  0.990086  0.877716  3.463870  545.000000   56.000000   1.0   5.000000   
6 -0.073939  0.177413  2.559143  705.000000   67.000000   1.0   6.000000   
7 -0.945785  0.423090  2.602685  203.000000   78.000000   1.0   7.000000   
8 -0.763080  0.882092  8.879926  773.000000   89.000000   1.0   8.000000   
9  0.426709  0.692333  4.066110  498.000000  100.000000   1.0   9.000000   

  unique      col8  
0      w  1.601452  
1      p  2.380143  
2      j  8.167601  
3      h  2.567220  
4      r  2.689671  
5      l  9.295631  
6      r  3.571635  
7      r  6.850922  
8      d  2.926981  
9      t  9.528417  
0    NaN  0.000000  
1    NaN  0.000000  
2    NaN  0.000000  
3    NaN  0.000000  
4    NaN  0.000000  
5    NaN  0.000000  
6    NaN  0.000000  
7    NaN  0.000000  
8    NaN  0.000000  
9    NaN  0.000000

In [188]:
concatedf_col = pd.concat([dflat1,df2lat1],axis=1)
concatedf_col

col1      col2      col3      col4      col5  col6       col7 unique  \
0  0.177947  0.225362  1.601452  0.284973  1.779399   0.0   5.590145      w   
1  0.184288  0.011343  2.380143  0.438632  2.564432   0.0   8.056399      p   
2  0.905873  0.909118  8.167601  7.398806  9.073474   0.0  28.505159      j   
3 -0.002695  0.693479  1.567220 -0.004224  1.564524  -1.0   4.915098      h   
4  0.702357  0.241503  2.689671  1.889109  3.392028   0.0  10.656370      r   
5  0.341921  0.182778  9.295631  3.178375  9.637553   0.0  30.277264      l   
6  1.257795  0.049831  3.571635  4.492386  4.829430   0.0  15.172103      r   
7 -0.241723  0.720601  5.850922 -1.414302  5.609199  -1.0  17.621818      r   
8  0.913589  0.654422  2.926981  2.674059  3.840571   0.0  12.065509      d   
9  0.199781  0.433508  9.528417  1.903597  9.728198   0.0  30.562035      t   

       col8      col1      col2      col3  col4   col5  col6  col7  col8  
0  1.601452  0.097709  0.494965  8.343930   586    1.0   1.0     0   0.0  
1  2.380143  1.101432  0.883264  1.675685   900   12.0   1.0     1   0.0  
2  8.167601 -1.433290  0.290166  9.889572   759   23.0   1.0     2   0.0  
3  2.567220 -1.385835  0.268615  9.761493   440   34.0   1.0     3   0.0  
4  2.689671  1.309157  0.381069  3.225178   441   45.0   1.0     4   0.0  
5  9.295631  0.990086  0.877716  3.463870   545   56.0   1.0     5   0.0  
6  3.571635 -0.073939  0.177413  2.559143   705   67.0   1.0     6   0.0  
7  6.850922 -0.945785  0.423090  2.602685   203   78.0   1.0     7   0.0  
8  2.926981 -0.763080  0.882092  8.879926   773   89.0   1.0     8   0.0  
9  9.528417  0.426709  0.692333  4.066110   498  100.0   1.0     9   0.0

In [189]:
concatedf.to_csv('Latihan Pertemuan 7', index=False)

# Latihan Numpy Pandas

In [3]:
# nomor 1
import numpy as np
import pandas as pd

a = int(input('Masukkan nilai awal : '))
b = int(input('Masukkan nilai akhir : '))

arr1D = np.arange(a,b)
arr1D

Masukkan nilai awal : 1
Masukkan nilai akhir : 28


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [4]:
arr1D.reshape(-1,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [6]:
arr1D.reshape(3,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [201]:
arr2D = arr1D.reshape(3,9)
arr2D

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [204]:
arr3D = arr1D.reshape(3,3,3)
arr3D

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [8]:
# nomor 2
N = int(input('Masukkan banyak angka yang diinginkan : '))
A = int(input('Masukkan angka awal : '))
Z = int(input('Masukkan angka akhir : '))

arr1d = np.random.randint(A,Z,N)
arr1d

Masukkan banyak angka yang diinginkan : 9
Masukkan angka awal : 1
Masukkan angka akhir : 100


array([60, 44, 72, 92, 25, 35, 20, 23, 48])

In [11]:
arr2d = arr1d.reshape(3,-1)
arr2d

array([[60, 44, 72],
       [92, 25, 35],
       [20, 23, 48]])

In [12]:
# tukar
arr2d[:,::-1]

array([[72, 44, 60],
       [35, 25, 92],
       [48, 23, 20]])

In [14]:
# nomor 3
arr3 = np.ones((10,10)) * 4
arr3[1:-1, 1:-1] = 0
arr3

array([[4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])

In [ ]:
# np.where(arr[1:-1, 1:-1])

In [220]:
# arr3[[0,-1]]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [231]:
# nomor 4
abjad = np.array(list(string.ascii_lowercase))
value = np.arange(1,27)

series = pd.Series(data=value, index=abjad)
series

a     1
b     2
c     3
d     4
e     5
f     6
g     7
h     8
i     9
j    10
k    11
l    12
m    13
n    14
o    15
p    16
q    17
r    18
s    19
t    20
u    21
v    22
w    23
x    24
y    25
z    26
dtype: int32

In [16]:
# nomor 5
series2 = pd.Series(np.random.randint(1,5,100))
series2

0     3
1     4
2     3
3     4
4     4
     ..
95    1
96    3
97    3
98    2
99    3
Length: 100, dtype: int32

In [19]:
x = series2.value_counts()
x

4    31
3    27
2    21
1    21
dtype: int64

In [22]:
print('Top 2 frekuensi adalah {} dengan frekuensi sebanyak {} dan {} dengan frekuensi sebanyak {}'.format(x.index[0], x.values[0], x.index[1], x[x.index[1]]))

Top 2 frekuensi adalah 4 dengan frekuensi sebanyak 31 dan 3 dengan frekuensi sebanyak 27


In [23]:
# nomor 6
import seaborn as sns
mpg = sns.load_dataset('mpg')
mpg.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   
4  17.0          8         302.0       140.0    3449          10.5   

   model_year origin                       name  
0          70    usa  chevrolet chevelle malibu  
1          70    usa          buick skylark 320  
2          70    usa         plymouth satellite  
3          70    usa              amc rebel sst  
4          70    usa                ford torino

In [24]:
mpg.describe(exclude='number')

origin        name
count     398         398
unique      3         305
top       usa  ford pinto
freq      249           6

In [241]:
mpg.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'name'],
      dtype='object')

In [25]:
mpg.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
name            0
dtype: int64

In [ ]:
mpg.isna().sum()/len(mpg)*100

In [26]:
# nomor 7
# Menampilkan missing value pada kolom horsepower
mpg[mpg['horsepower'].isna()]

mpg  cylinders  displacement  horsepower  weight  acceleration  \
32   25.0          4          98.0         NaN    2046          19.0   
126  21.0          6         200.0         NaN    2875          17.0   
330  40.9          4          85.0         NaN    1835          17.3   
336  23.6          4         140.0         NaN    2905          14.3   
354  34.5          4         100.0         NaN    2320          15.8   
374  23.0          4         151.0         NaN    3035          20.5   

     model_year  origin                  name  
32           71     usa            ford pinto  
126          74     usa         ford maverick  
330          80  europe  renault lecar deluxe  
336          80     usa    ford mustang cobra  
354          81  europe           renault 18i  
374          82     usa        amc concord dl

In [27]:
# Menampilkan index pada missing value
print('daftar index missing value')
mpg[mpg['horsepower'].isna()].index

daftar index missing value


Int64Index([32, 126, 330, 336, 354, 374], dtype='int64')

In [8]:
# nomor 8
mpg.groupby('origin').mean()['horsepower']

origin
europe     80.558824
japan      79.835443
usa       119.048980
Name: horsepower, dtype: float64

In [28]:
def fillho(a):
    if a['horsepower'] <= 105:
        return 'lower {}'.format(a['origin']) 
    else:
        return 'upper {}'.format(a['origin'])

In [30]:
# nomor 9
mpg['horse_origin'] = mpg[['horsepower', 'origin']].apply(fillho,axis=1)

In [31]:
mpg

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model_year  origin                       name  horse_origin  
0            70     usa  chevrolet chevelle malibu     upper usa  
1            70     usa          buick skylark 320     upper usa  
2            70     usa         plymouth satellite     upper usa  
3            70     usa              amc rebel sst     upper usa  
4            70     usa                ford torino     upper usa  
..          ...     ...                        ...           ...  
393          82     usa            ford mustang gl     lower usa  
394          82  europe                  vw pickup  lower europe  
395          82     usa              dodge rampage     lower usa  
396          82     usa                ford ranger     lower usa  
397          82     usa                 chevy s-10     lower usa  

[398 rows x 10 columns]

In [35]:
# nomor 10
mpg.groupby('origin').agg(['mean','std','sum','count','min','max'])

mpg                                     cylinders            \
             mean       std     sum count   min   max      mean       std   
origin                                                                      
europe  27.891429  6.723930  1952.4    70  16.2  44.3  4.157143  0.500310   
japan   30.450633  6.090048  2405.6    79  18.0  46.6  4.101266  0.590414   
usa     20.083534  6.402892  5000.8   249   9.0  39.0  6.248996  1.661425   

                    ... acceleration                   model_year            \
         sum count  ...          sum count   min   max       mean       std   
origin              ...                                                       
europe   291    70  ...       1175.1    70  12.2  24.8  75.814286  3.469506   
japan    324    79  ...       1277.6    79  11.4  21.0  77.443038  3.650595   
usa     1556   249  ...       3743.4   249   8.0  22.2  75.610442  3.677094   

                             
          sum count min max  
origin                       
europe   5307    70  70  82  
japan    6118    79  70  82  
usa     18827   249  70  82  

[3 rows x 42 columns]

In [42]:
mpg.mean()['weight']

2970.424623115578

In [43]:
mpg.groupby('origin').agg(['mean','std','sum','count','min','max'])['weight']

mean         std     sum  count   min   max
origin                                                    
europe  2423.300000  490.043191  169631     70  1825  3820
japan   2221.227848  320.497248  175477     79  1613  2930
usa     3361.931727  794.792506  837121    249  1800  5140