# Latihan Numpy Pandas

In [3]:
# nomor 1
import numpy as np
import pandas as pd

a = int(input('Masukkan nilai awal : '))
b = int(input('Masukkan nilai akhir : '))

arr1D = np.arange(a,b)
arr1D

Masukkan nilai awal : 1
Masukkan nilai akhir : 28


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [4]:
arr1D.reshape(-1,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [6]:
arr1D.reshape(3,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [201]:
arr2D = arr1D.reshape(3,9)
arr2D

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [204]:
arr3D = arr1D.reshape(3,3,3)
arr3D

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [8]:
# nomor 2
N = int(input('Masukkan banyak angka yang diinginkan : '))
A = int(input('Masukkan angka awal : '))
Z = int(input('Masukkan angka akhir : '))

arr1d = np.random.randint(A,Z,N)
arr1d

Masukkan banyak angka yang diinginkan : 9
Masukkan angka awal : 1
Masukkan angka akhir : 100


array([60, 44, 72, 92, 25, 35, 20, 23, 48])

In [11]:
arr2d = arr1d.reshape(3,-1)
arr2d

array([[60, 44, 72],
       [92, 25, 35],
       [20, 23, 48]])

In [12]:
# tukar
arr2d[:,::-1]

array([[72, 44, 60],
       [35, 25, 92],
       [48, 23, 20]])

In [14]:
# nomor 3
arr3 = np.ones((10,10)) * 4
arr3[1:-1, 1:-1] = 0
arr3

array([[4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])

In [ ]:
# np.where(arr[1:-1, 1:-1])

In [220]:
# arr3[[0,-1]]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [231]:
# nomor 4
abjad = np.array(list(string.ascii_lowercase))
value = np.arange(1,27)

series = pd.Series(data=value, index=abjad)
series

a     1
b     2
c     3
d     4
e     5
f     6
g     7
h     8
i     9
j    10
k    11
l    12
m    13
n    14
o    15
p    16
q    17
r    18
s    19
t    20
u    21
v    22
w    23
x    24
y    25
z    26
dtype: int32

In [16]:
# nomor 5
series2 = pd.Series(np.random.randint(1,5,100))
series2

0     3
1     4
2     3
3     4
4     4
     ..
95    1
96    3
97    3
98    2
99    3
Length: 100, dtype: int32

In [19]:
x = series2.value_counts()
x

4    31
3    27
2    21
1    21
dtype: int64

In [22]:
print('Top 2 frekuensi adalah {} dengan frekuensi sebanyak {} dan {} dengan frekuensi sebanyak {}'.format(x.index[0], x.values[0], x.index[1], x[x.index[1]]))

Top 2 frekuensi adalah 4 dengan frekuensi sebanyak 31 dan 3 dengan frekuensi sebanyak 27


In [23]:
# nomor 6
import seaborn as sns
mpg = sns.load_dataset('mpg')
mpg.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   
4  17.0          8         302.0       140.0    3449          10.5   

   model_year origin                       name  
0          70    usa  chevrolet chevelle malibu  
1          70    usa          buick skylark 320  
2          70    usa         plymouth satellite  
3          70    usa              amc rebel sst  
4          70    usa                ford torino

In [24]:
mpg.describe(exclude='number')

origin        name
count     398         398
unique      3         305
top       usa  ford pinto
freq      249           6

In [241]:
mpg.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'name'],
      dtype='object')

In [25]:
mpg.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
name            0
dtype: int64

In [ ]:
mpg.isna().sum()/len(mpg)*100

In [26]:
# nomor 7
# Menampilkan missing value pada kolom horsepower
mpg[mpg['horsepower'].isna()]

mpg  cylinders  displacement  horsepower  weight  acceleration  \
32   25.0          4          98.0         NaN    2046          19.0   
126  21.0          6         200.0         NaN    2875          17.0   
330  40.9          4          85.0         NaN    1835          17.3   
336  23.6          4         140.0         NaN    2905          14.3   
354  34.5          4         100.0         NaN    2320          15.8   
374  23.0          4         151.0         NaN    3035          20.5   

     model_year  origin                  name  
32           71     usa            ford pinto  
126          74     usa         ford maverick  
330          80  europe  renault lecar deluxe  
336          80     usa    ford mustang cobra  
354          81  europe           renault 18i  
374          82     usa        amc concord dl

In [27]:
# Menampilkan index pada missing value
print('daftar index missing value')
mpg[mpg['horsepower'].isna()].index

daftar index missing value


Int64Index([32, 126, 330, 336, 354, 374], dtype='int64')

In [8]:
# nomor 8
mpg.groupby('origin').mean()['horsepower']

origin
europe     80.558824
japan      79.835443
usa       119.048980
Name: horsepower, dtype: float64

In [28]:
def fillho(a):
    if a['horsepower'] <= 105:
        return 'lower {}'.format(a['origin']) 
    else:
        return 'upper {}'.format(a['origin'])

In [30]:
# nomor 9
mpg['horse_origin'] = mpg[['horsepower', 'origin']].apply(fillho,axis=1)

In [31]:
mpg

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model_year  origin                       name  horse_origin  
0            70     usa  chevrolet chevelle malibu     upper usa  
1            70     usa          buick skylark 320     upper usa  
2            70     usa         plymouth satellite     upper usa  
3            70     usa              amc rebel sst     upper usa  
4            70     usa                ford torino     upper usa  
..          ...     ...                        ...           ...  
393          82     usa            ford mustang gl     lower usa  
394          82  europe                  vw pickup  lower europe  
395          82     usa              dodge rampage     lower usa  
396          82     usa                ford ranger     lower usa  
397          82     usa                 chevy s-10     lower usa  

[398 rows x 10 columns]

In [35]:
# nomor 10
mpg.groupby('origin').agg(['mean','std','sum','count','min','max'])

mpg                                     cylinders            \
             mean       std     sum count   min   max      mean       std   
origin                                                                      
europe  27.891429  6.723930  1952.4    70  16.2  44.3  4.157143  0.500310   
japan   30.450633  6.090048  2405.6    79  18.0  46.6  4.101266  0.590414   
usa     20.083534  6.402892  5000.8   249   9.0  39.0  6.248996  1.661425   

                    ... acceleration                   model_year            \
         sum count  ...          sum count   min   max       mean       std   
origin              ...                                                       
europe   291    70  ...       1175.1    70  12.2  24.8  75.814286  3.469506   
japan    324    79  ...       1277.6    79  11.4  21.0  77.443038  3.650595   
usa     1556   249  ...       3743.4   249   8.0  22.2  75.610442  3.677094   

                             
          sum count min max  
origin                       
europe   5307    70  70  82  
japan    6118    79  70  82  
usa     18827   249  70  82  

[3 rows x 42 columns]

In [42]:
mpg.mean()['weight']

2970.424623115578

In [43]:
mpg.groupby('origin').agg(['mean','std','sum','count','min','max'])['weight']

mean         std     sum  count   min   max
origin                                                    
europe  2423.300000  490.043191  169631     70  1825  3820
japan   2221.227848  320.497248  175477     79  1613  2930
usa     3361.931727  794.792506  837121    249  1800  5140